#!/usr/bin/env bun

import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then(async (x) => {
      if (!x.ok) throw new Error(`Failed to fetch models: ${x.statusText}`)
      const text = await x.text()
      try {
        JSON.parse(text)
      } catch {
        throw new Error(`Invalid JSON from ${modelsUrl}/api.json`)
      }
      return text
    })
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
// Build all targets in parallel for faster CI times
await Promise.all(
  targets.map(async (item) => {
    const name = [
      pkg.name,
      // changing to win32 flags npm for some reason
      item.os === "win32" ? "windows" : item.os,
      item.arch,
      item.avx2 === false ? "baseline" : undefined,
      item.abi === undefined ? undefined : item.abi,
    ]
      .filter(Boolean)
      .join("-")
    console.log(`building ${name}`)
    await $`mkdir -p dist/${name}/bin`

    const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
    const workerPath = "./src/cli/cmd/tui/worker.ts"

    // Use platform-specific bunfs root path based on target OS
    const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
    const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

    await Bun.build({
      conditions: ["browser"],
      tsconfig: "./tsconfig.json",
      plugins: [solidPlugin],
      sourcemap: "external",
      compile: {
        autoloadBunfig: false,
        autoloadDotenv: false,
        //@ts-ignore (bun types aren't up to date)
        autoloadTsconfig: true,
        autoloadPackageJson: true,
        target: name.replace(pkg.name, "bun") as any,
        outfile: `dist/${name}/bin/opencode`,
        execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
        windows: {},
      },
      entrypoints: ["./src/index.ts", parserWorker, workerPath],
      define: {
        OPENCODE_VERSION: `'${Script.version}'`,
        OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
        OPENCODE_WORKER_PATH: workerPath,
        OPENCODE_CHANNEL: `'${Script.channel}'`,
        OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      },
    })

    await $`rm -rf ./dist/${name}/bin/tui`
    await Bun.file(`dist/${name}/package.json`).write(
      JSON.stringify(
        {
          name,
          version: Script.version,
          os: [item.os],
          cpu: [item.arch],
        },
        null,
        2,
      ),
    )
    binaries[name] = Script.version
  }),
)

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.dist/*.tar.gz --clobber`
}

// Check if server.ts has been modified since last SDK generation
const serverPath = path.join(dir, "src/server/server.ts")
const sdkPath = path.join(dir, "../../packages/sdk/js/src/index.ts")
if (fs.existsSync(serverPath) && fs.existsSync(sdkPath)) {
  const serverStat = fs.statSync(serverPath)
  const sdkStat = fs.statSync(sdkPath)

  if (serverStat.mtime > sdkStat.mtime) {
    console.warn("\n⚠️  WARNING: src/server/server.ts has been modified since last SDK generation!")
    console.warn("   Run: ./script/generate.ts to regenerate the SDK and related files.")
    console.warn("   See AGENTS.md for details.\n")
  }
}

export { binaries }
